---
# Copyleft (c) 2022 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    DataPackageFrictionlessData: 
      $ref: "https://smart-data-models.github.io/dataModel.FrictionlessData/DataPackageFrictionlessData/model.yaml#/DataPackageFrictionlessData"
info:
  description:  |
    Data Package is a simple specification for data access and delivery.Converted for Smart Data Models initiative from original frictionless data
  title: DataPackageFrictionlessData
  version: "0.0.3"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - DataPackageFrictionlessData
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.FrictionlessData/DataPackageFrictionlessData/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.FrictionlessData/DataPackageFrictionlessData/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
